twig:
    file_name_pattern: '*.twig'
    globals:
        moderation: '@App\Twig\ModeratorExtension'
        nbrMessage: '@App\Twig\MessageExtension'
        nbrReservation: '@App\Twig\ReservationExtension'

    paths:
        '%kernel.project_dir%/assets/images/email': email_images
        '%kernel.project_dir%/assets/styles': styles
        
      

when@test:
    twig:
        strict_variables: true
